export const RESEND_VALIDATION_EMAIL_REQUEST = 'RESEND_VALIDATION_EMAIL_REQUEST';
export const RESEND_VALIDATION_EMAIL_SUCCESS = 'RESEND_VALIDATION_EMAIL_SUCCESS';
export const RESEND_VALIDATION_EMAIL_FAIL = 'RESEND_VALIDATION_EMAIL_FAIL';
