export const LOAD_NEWS_REQUEST = 'LOAD_NEWS_REQUEST';
export const LOAD_NEWS_SUCCESS = 'LOAD_NEWS_SUCCESS';
export const LOAD_NEWS_FAIL = 'LOAD_NEWS_FAIL';

export const LOAD_NEWS_PAGE_REQUEST = 'LOAD_NEWS_PAGE_REQUEST';
export const LOAD_NEWS_PAGE_SUCCESS = 'LOAD_NEWS_PAGE_SUCCESS';
export const LOAD_NEWS_PAGE_FAIL = 'LOAD_NEWS_PAGE_FAIL';
