export const LOAD_ORDERS_REQUEST = 'LOAD_ORDERS_REQUEST';
export const LOAD_ORDERS_SUCCESS = 'LOAD_ORDERS_SUCCESS';
export const LOAD_ORDERS_FAIL = 'LOAD_ORDERS_FAIL';

export const LOAD_ORDER_SPEC_REQUEST = 'LOAD_ORDER_SPEC_REQUEST';
export const LOAD_ORDER_SPEC_SUCCESS = 'LOAD_ORDER_SPEC_SUCCESS';
export const LOAD_ORDER_SPEC_FAIL = 'LOAD_ORDER_SPEC_FAIL';
export const INVALIDATE_ORDER_SPEC = 'INVALIDATE_ORDER_SPEC';
