export const LOAD_PRODUCT_CATEGORIES_REQUEST = 'LOAD_PRODUCT_CATEGORIES_REQUEST';
export const LOAD_PRODUCT_CATEGORIES_FAIL = 'LOAD_PRODUCT_CATEGORIES_FAIL';
export const LOAD_PRODUCT_CATEGORIES_SUCCESS = 'LOAD_PRODUCT_CATEGORIES_SUCCESS';

export const SELECT_PRODUCT_CATEGORY = 'SELECT_PRODUCT_CATEGORY';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const SET_OPENED = 'SET_OPENED';

export const LOAD_PRODUCTS_REQUEST = 'LOAD_PRODUCTS_REQUEST';
export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';
export const LOAD_PRODUCTS_FAIL = 'LOAD_PRODUCTS_FAIL';

export const LOAD_PRODUCTS_LENGTH_REQUEST = 'LOAD_PRODUCTS_LENGTH_REQUEST';
export const LOAD_PRODUCTS_LENGTH_SUCCESS = 'LOAD_PRODUCTS_LENGTH_SUCCESS';
export const LOAD_PRODUCTS_LENGTH_FAIL = 'LOAD_PRODUCTS_LENGTH_FAIL';


//export const TUNE_CHILDS_VIEW = 'TUNE_CHILDS_VIEW';
