export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_FAIL = 'LOGIN_FAIL'
//export const EMAIL_NEED_VALIDATE = 'EMAIL_NEED_VALIDATE'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const LOGOUT_SUCCESS='LOGOUT_SUCCESS'

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'

export const VALIDATE_EMAIL_REQUEST = 'VALIDATE_EMAIL_REQUEST';
export const VALIDATE_EMAIL_SUCCESS = 'VALIDATE_EMAIL_SUCCESS';
export const VALIDATE_EMAIL_FAIL = 'VALIDATE_EMAIL_FAIL';

export const ME_FROM_TOKEN_REQUEST = 'ME_FROM_TOKEN_REQUEST';
export const ME_FROM_TOKEN_SUCCESS = 'ME_FROM_TOKEN_SUCCESS';
export const ME_FROM_TOKEN_FAIL = 'ME_FROM_TOKEN_FAIL';

export const RESET_TOKEN = 'RESET_TOKEN';
//export const RESET_RESEND_EMAIL_STATE = 'RESET_RESEND_EMAIL_STATE';
